# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 901)
        MainWindow.setMinimumSize(QtCore.QSize(960, 800))
        MainWindow.setMaximumSize(QtCore.QSize(960, 1080))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.main_board_frame = QtGui.QFrame(self.centralwidget)
        self.main_board_frame.setGeometry(QtCore.QRect(50, 50, 557, 557))
        self.main_board_frame.setMaximumSize(QtCore.QSize(557, 557))
        self.main_board_frame.setObjectName(_fromUtf8("main_board_frame"))
        self.y_label_widget = QtGui.QWidget(self.centralwidget)
        self.y_label_widget.setGeometry(QtCore.QRect(20, 50, 30, 557))
        self.y_label_widget.setObjectName(_fromUtf8("y_label_widget"))
        self.x_label_widget = QtGui.QWidget(self.centralwidget)
        self.x_label_widget.setGeometry(QtCore.QRect(50, 20, 557, 30))
        self.x_label_widget.setObjectName(_fromUtf8("x_label_widget"))
        self.settings_widget = QtGui.QWidget(self.centralwidget)
        self.settings_widget.setGeometry(QtCore.QRect(620, 50, 321, 131))
        self.settings_widget.setObjectName(_fromUtf8("settings_widget"))
        self.language_box = QtGui.QComboBox(self.settings_widget)
        self.language_box.setGeometry(QtCore.QRect(110, 10, 201, 22))
        self.language_box.setObjectName(_fromUtf8("language_box"))
        self.language_label = QtGui.QLabel(self.settings_widget)
        self.language_label.setGeometry(QtCore.QRect(20, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.language_label.setFont(font)
        self.language_label.setObjectName(_fromUtf8("language_label"))
        self.dictionary_label = QtGui.QLabel(self.settings_widget)
        self.dictionary_label.setGeometry(QtCore.QRect(20, 40, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dictionary_label.setFont(font)
        self.dictionary_label.setObjectName(_fromUtf8("dictionary_label"))
        self.dictionary_box = QtGui.QComboBox(self.settings_widget)
        self.dictionary_box.setGeometry(QtCore.QRect(110, 40, 201, 22))
        self.dictionary_box.setObjectName(_fromUtf8("dictionary_box"))
        self.game_type_label = QtGui.QLabel(self.settings_widget)
        self.game_type_label.setGeometry(QtCore.QRect(20, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label.setFont(font)
        self.game_type_label.setObjectName(_fromUtf8("game_type_label"))
        self.game_type_box = QtGui.QComboBox(self.settings_widget)
        self.game_type_box.setGeometry(QtCore.QRect(110, 70, 201, 22))
        self.game_type_box.setObjectName(_fromUtf8("game_type_box"))
        self.debug_mode_button = QtGui.QRadioButton(self.settings_widget)
        self.debug_mode_button.setGeometry(QtCore.QRect(210, 100, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.debug_mode_button.setFont(font)
        self.debug_mode_button.setObjectName(_fromUtf8("debug_mode_button"))
        self.stats_widget = QtGui.QWidget(self.centralwidget)
        self.stats_widget.setGeometry(QtCore.QRect(620, 210, 321, 391))
        self.stats_widget.setObjectName(_fromUtf8("stats_widget"))
        self.player1_label = QtGui.QLabel(self.stats_widget)
        self.player1_label.setGeometry(QtCore.QRect(10, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.player1_label.setFont(font)
        self.player1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.player1_label.setObjectName(_fromUtf8("player1_label"))
        self.player1_label_2 = QtGui.QLabel(self.stats_widget)
        self.player1_label_2.setGeometry(QtCore.QRect(10, 210, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.player1_label_2.setFont(font)
        self.player1_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.player1_label_2.setObjectName(_fromUtf8("player1_label_2"))
        self.player1_selection_box = QtGui.QComboBox(self.stats_widget)
        self.player1_selection_box.setGeometry(QtCore.QRect(110, 10, 201, 22))
        self.player1_selection_box.setObjectName(_fromUtf8("player1_selection_box"))
        self.player2_selection_box = QtGui.QComboBox(self.stats_widget)
        self.player2_selection_box.setGeometry(QtCore.QRect(110, 210, 201, 22))
        self.player2_selection_box.setObjectName(_fromUtf8("player2_selection_box"))
        self.game_type_label_2 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_2.setGeometry(QtCore.QRect(20, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_2.setFont(font)
        self.game_type_label_2.setObjectName(_fromUtf8("game_type_label_2"))
        self.player1_score_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player1_score_lcd.setGeometry(QtCore.QRect(70, 40, 64, 23))
        self.player1_score_lcd.setObjectName(_fromUtf8("player1_score_lcd"))
        self.game_type_label_3 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_3.setGeometry(QtCore.QRect(20, 70, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_3.setFont(font)
        self.game_type_label_3.setObjectName(_fromUtf8("game_type_label_3"))
        self.player1_avg_word_score_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player1_avg_word_score_lcd.setGeometry(QtCore.QRect(180, 70, 64, 23))
        self.player1_avg_word_score_lcd.setObjectName(_fromUtf8("player1_avg_word_score_lcd"))
        self.game_type_label_4 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_4.setGeometry(QtCore.QRect(20, 130, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_4.setFont(font)
        self.game_type_label_4.setObjectName(_fromUtf8("game_type_label_4"))
        self.game_type_label_5 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_5.setGeometry(QtCore.QRect(20, 100, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_5.setFont(font)
        self.game_type_label_5.setObjectName(_fromUtf8("game_type_label_5"))
        self.player1_top_word_score_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player1_top_word_score_lcd.setGeometry(QtCore.QRect(180, 100, 64, 23))
        self.player1_top_word_score_lcd.setObjectName(_fromUtf8("player1_top_word_score_lcd"))
        self.player1_top_word_line = QtGui.QLineEdit(self.stats_widget)
        self.player1_top_word_line.setGeometry(QtCore.QRect(110, 130, 201, 20))
        self.player1_top_word_line.setReadOnly(True)
        self.player1_top_word_line.setObjectName(_fromUtf8("player1_top_word_line"))
        self.game_type_label_6 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_6.setGeometry(QtCore.QRect(170, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_6.setFont(font)
        self.game_type_label_6.setObjectName(_fromUtf8("game_type_label_6"))
        self.player1_turns_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player1_turns_lcd.setGeometry(QtCore.QRect(220, 40, 64, 23))
        self.player1_turns_lcd.setObjectName(_fromUtf8("player1_turns_lcd"))
        self.player2_longest_word_line = QtGui.QLineEdit(self.stats_widget)
        self.player2_longest_word_line.setGeometry(QtCore.QRect(110, 160, 201, 20))
        self.player2_longest_word_line.setText(_fromUtf8(""))
        self.player2_longest_word_line.setReadOnly(True)
        self.player2_longest_word_line.setObjectName(_fromUtf8("player2_longest_word_line"))
        self.game_type_label_7 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_7.setGeometry(QtCore.QRect(20, 160, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_7.setFont(font)
        self.game_type_label_7.setObjectName(_fromUtf8("game_type_label_7"))
        self.player2_turns_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player2_turns_lcd.setGeometry(QtCore.QRect(220, 240, 64, 23))
        self.player2_turns_lcd.setObjectName(_fromUtf8("player2_turns_lcd"))
        self.player2_avg_word_score_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player2_avg_word_score_lcd.setGeometry(QtCore.QRect(180, 270, 64, 23))
        self.player2_avg_word_score_lcd.setObjectName(_fromUtf8("player2_avg_word_score_lcd"))
        self.game_type_label_8 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_8.setGeometry(QtCore.QRect(20, 270, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_8.setFont(font)
        self.game_type_label_8.setObjectName(_fromUtf8("game_type_label_8"))
        self.game_type_label_9 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_9.setGeometry(QtCore.QRect(20, 300, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_9.setFont(font)
        self.game_type_label_9.setObjectName(_fromUtf8("game_type_label_9"))
        self.player2_top_word_score_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player2_top_word_score_lcd.setGeometry(QtCore.QRect(180, 300, 64, 23))
        self.player2_top_word_score_lcd.setObjectName(_fromUtf8("player2_top_word_score_lcd"))
        self.player2_top_word_line = QtGui.QLineEdit(self.stats_widget)
        self.player2_top_word_line.setGeometry(QtCore.QRect(110, 330, 201, 20))
        self.player2_top_word_line.setText(_fromUtf8(""))
        self.player2_top_word_line.setReadOnly(True)
        self.player2_top_word_line.setObjectName(_fromUtf8("player2_top_word_line"))
        self.game_type_label_10 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_10.setGeometry(QtCore.QRect(20, 240, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_10.setFont(font)
        self.game_type_label_10.setObjectName(_fromUtf8("game_type_label_10"))
        self.game_type_label_11 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_11.setGeometry(QtCore.QRect(170, 240, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_11.setFont(font)
        self.game_type_label_11.setObjectName(_fromUtf8("game_type_label_11"))
        self.game_type_label_12 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_12.setGeometry(QtCore.QRect(20, 330, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_12.setFont(font)
        self.game_type_label_12.setObjectName(_fromUtf8("game_type_label_12"))
        self.game_type_label_13 = QtGui.QLabel(self.stats_widget)
        self.game_type_label_13.setGeometry(QtCore.QRect(20, 360, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.game_type_label_13.setFont(font)
        self.game_type_label_13.setObjectName(_fromUtf8("game_type_label_13"))
        self.player2_score_lcd = QtGui.QLCDNumber(self.stats_widget)
        self.player2_score_lcd.setGeometry(QtCore.QRect(70, 240, 64, 23))
        self.player2_score_lcd.setObjectName(_fromUtf8("player2_score_lcd"))
        self.player2_longest_word_line_2 = QtGui.QLineEdit(self.stats_widget)
        self.player2_longest_word_line_2.setGeometry(QtCore.QRect(110, 360, 201, 20))
        self.player2_longest_word_line_2.setText(_fromUtf8(""))
        self.player2_longest_word_line_2.setReadOnly(True)
        self.player2_longest_word_line_2.setObjectName(_fromUtf8("player2_longest_word_line_2"))
        self.player_area_widget = QtGui.QWidget(self.centralwidget)
        self.player_area_widget.setGeometry(QtCore.QRect(20, 620, 921, 231))
        self.player_area_widget.setObjectName(_fromUtf8("player_area_widget"))
        self.player1_label_pa = QtGui.QLabel(self.player_area_widget)
        self.player1_label_pa.setGeometry(QtCore.QRect(190, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.player1_label_pa.setFont(font)
        self.player1_label_pa.setAlignment(QtCore.Qt.AlignCenter)
        self.player1_label_pa.setObjectName(_fromUtf8("player1_label_pa"))
        self.player2_label_pq = QtGui.QLabel(self.player_area_widget)
        self.player2_label_pq.setGeometry(QtCore.QRect(540, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.player2_label_pq.setFont(font)
        self.player2_label_pq.setAlignment(QtCore.Qt.AlignCenter)
        self.player2_label_pq.setObjectName(_fromUtf8("player2_label_pq"))
        self.player2_show_tiles_button = QtGui.QRadioButton(self.player_area_widget)
        self.player2_show_tiles_button.setGeometry(QtCore.QRect(730, 10, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.player2_show_tiles_button.setFont(font)
        self.player2_show_tiles_button.setObjectName(_fromUtf8("player2_show_tiles_button"))
        self.player1_tiles = QtGui.QWidget(self.player_area_widget)
        self.player1_tiles.setGeometry(QtCore.QRect(40, 40, 382, 39))
        self.player1_tiles.setObjectName(_fromUtf8("player1_tiles"))
        self.player2_tiles = QtGui.QWidget(self.player_area_widget)
        self.player2_tiles.setGeometry(QtCore.QRect(500, 40, 382, 39))
        self.player2_tiles.setObjectName(_fromUtf8("player2_tiles"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.language_label.setText(_translate("MainWindow", "Language", None))
        self.dictionary_label.setText(_translate("MainWindow", "Dictionary", None))
        self.game_type_label.setText(_translate("MainWindow", "Game Type", None))
        self.debug_mode_button.setText(_translate("MainWindow", "Debug Mode", None))
        self.player1_label.setText(_translate("MainWindow", "Player 1", None))
        self.player1_label_2.setText(_translate("MainWindow", "Player 2", None))
        self.game_type_label_2.setText(_translate("MainWindow", "Score", None))
        self.game_type_label_3.setText(_translate("MainWindow", "Avg. Word Score", None))
        self.game_type_label_4.setText(_translate("MainWindow", "Top Word", None))
        self.game_type_label_5.setText(_translate("MainWindow", "Top Word Score", None))
        self.game_type_label_6.setText(_translate("MainWindow", "Turns", None))
        self.game_type_label_7.setText(_translate("MainWindow", "Longest W.", None))
        self.game_type_label_8.setText(_translate("MainWindow", "Avg. Word Score", None))
        self.game_type_label_9.setText(_translate("MainWindow", "Top Word Score", None))
        self.game_type_label_10.setText(_translate("MainWindow", "Score", None))
        self.game_type_label_11.setText(_translate("MainWindow", "Turns", None))
        self.game_type_label_12.setText(_translate("MainWindow", "Top Word", None))
        self.game_type_label_13.setText(_translate("MainWindow", "Longest W.", None))
        self.player1_label_pa.setText(_translate("MainWindow", "Player 1", None))
        self.player2_label_pq.setText(_translate("MainWindow", "Player 2", None))
        self.player2_show_tiles_button.setText(_translate("MainWindow", "Show Tiles", None))

